### ISSUE TITLE
Questions about your fork and attribution restoration

### ISSUE THREAD

**Issue by nekusu** [mcxleague/chimptype#6]
Hello mcxleague,

I recently came across your fork of [apetype](https://github.com/nekusu/apetype), it's great to see the project being explored and expanded upon. I wanted to reach out to you and express my curiosity about your decision to maintain a separate fork instead of contributing directly to the original project. Open source projects thrive on collaboration, and I am always open to contributions that enhance the overall experience of the platform.

If there are specific reasons for maintaining a separate fork, I'd be interested in understanding them. Furthermore, I kindly request that you provide proper attribution for the original work. The GPL-3.0 license requires that derivative works also be released under the same license, and it emphasizes the preservation of copyright notices and license information. This includes maintaining references to the original project and contributors.

In particular, the removal of the button with my name linking to my GitHub profile in the footer *may* be considered a violation of the GPL-3.0, which requires the preservation of such attribution. I kindly ask that you restore the original attribution in accordance with the license.

I appreciate your time and consideration. Please feel free to respond here or contact me directly if you have any questions or concerns.

Thank you,
nekusu

**Comment by mcxleague** [comment]
Hello there, I will add back the link to your GitHub in the footer of my site. My reason for forking your repository is for a school project, my teacher wanted me to make a typing website similar to monkey type with added features for sharing student typing speed, etc. with the teacher. If you have any other concerns feel free to reach out!

**Comment by nekusu** [comment]
Thanks for your quick response and for being open about the attribution concern. I appreciate your transparency regarding the purpose of the fork.

I'm glad to hear that you'll be adding back the link to my GitHub, totally good with just that. If you ever decide to add a README file later on, including the link there would be greatly appreciated. If you have any questions or need help, feel free to hit me up on Discord, it's better for quick communication. My username there is also nekusu.

Best of luck with your school project!
